# Generated by Django 4.2.5 on 2023-10-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='publis_date',
            new_name='publish_date',
        ),
    ]
